### ISSUE TITLE
HTML/XML to SemanticWeb::Schema::*

### ISSUE THREAD

**Issue by merkys** [robrwo/SemanticWeb-Schema#4]
Are there any plans to develop a reader from HTML/XML into `SemanticWeb::Schema::*` objects?

**Comment by robrwo** [comment]
No, only JSON-LD is supported.

PRs for supporting RDFa or Microdata are welcome, but it's probably easier to develop a separate distribution that parses data, especially since the version numbers of this are tied to the schema.org versions.

**Comment by merkys** [comment]
I see. I just saw that Microdata parsers are available (for example [HTML::HTML5::Microdata::Parser](https://metacpan.org/pod/HTML::HTML5::Microdata::Parser)). I might venture into writing glue code.
